LTP:Fix failure setresuid syscall test setresuid04
lsds/sgx-lkl pull request #166
Opened 2020-05-04 15:25 UTC by shaikshavali1

Test case (testcases/kernel/syscalls/setresuid/setresuid04)
is failed/skipped because it exit improperly in middle of test.
this is due to single process environment. Test case is modified
and updated to test setresuid syscall in multithreaded environment

2020-05-04 18:59 UTC, hukoyu approved these changes
Looks good to me. @letmaik can you also review and merge if looks good? Thanks.

2020-05-05 08:03 UTC, letmaik requested changes

2020-05-05 08:03 UTC, letmaik commented on tests/ltp/batch.mk
> +	$(ESCALATE_CMD) cp ../patches/fix_setresuid_setresuid04.patch $(MOUNTPOINT)/
Is there a reason why this patch is in a different folder than the other patch?

2020-05-05 08:03 UTC, letmaik commented on tests/ltp/buildenv.sh
> +    if [ -f $FIX_SETRESUID_PATCH ];then
As in the other PR, is this necessary?

2020-05-05 08:03 UTC, letmaik commented on tests/ltp/patches/fix_setresuid_setresuid04.patch
> + TCID_DEFINE(setresuid04);
Please add a comment on what this patch is doing and why it's necessary.

2020-05-05 08:03 UTC, letmaik commented on tests/ltp/patches/fix_setresuid_setresuid04.patch
> ++	/* Test to open the file in son process */
What' a `son process`?

2020-05-06 16:53 UTC, shaikshavali1 commented
Created new Consolidated PR "https://github.com/lsds/sgx-lkl/pull/201" which includes  current PR changes as well.

2020-05-06 16:53 UTC, closed without merging