Fix for fgetxattr01,preadv203,renameat01,statx01
lsds/sgx-lkl pull request #253
Opened 2020-05-15 04:34 UTC by ashokchandran

Issue: These tests were failing with panic due to out of memory.
Solution: Loop file system cannot be used for these tests as Kernel Memory is set to 32M. So fix is to use root file system.

2020-05-15 18:44 UTC, hukoyu requested changes

2020-05-15 18:44 UTC, hukoyu commented on tests/ltp/patches/fgetxattr01.patch
> + # include <sys/xattr.h>
'#include'

2020-05-18 10:25 UTC, shaikshavali1 commented on tests/ltp/patches/fgetxattr01.patch
> ++/* Patch to use root file system for the test as loop device file
Use single line (//) comments instead of block comments ( /* */ ).

2020-05-18 10:25 UTC, shaikshavali1 commented on tests/ltp/patches/fgetxattr01.patch
> +diff --git a/testcases/kernel/syscalls/fgetxattr/fgetxattr01.c b/testcases/kernel/syscalls/fgetxattr/fgetxattr01.c
Add some description about the patch in .patch file. Why this change is necessary? And what is the change?

2020-05-19 07:03 UTC, ashokchandran commented
@letmaik The pipeline check faling is not related to my changes. So please rerun the failed jobs (Since we dont have permission.) 
"languages-java-read_file-(debug)-(run-sw)-(8-ethreads)
Test 'languages-java-read_file-(debug)-(run-sw)-(8-ethreads)' status - failed (Exit code: '124'; FAILURES in output: '0').. "

2020-05-19 17:30 UTC, hukoyu approved these changes
Reran the failed jobs in pipeline and passed. LGTM. cc @letmaik

2020-05-19 18:49 UTC, letmaik approved these changes

2020-05-19 18:49 UTC, merged