LTP: Fixed fremovexattr 01 and 02 tests
lsds/sgx-lkl pull request #292
Opened 2020-05-21 17:01 UTC by vamsikrishna935

Tests were modified to use root file system.

2020-05-21 17:46 UTC, hukoyu requested changes
Use SAFE_* frammework provided methods

2020-05-21 17:46 UTC, hukoyu commented on tests/ltp/patches/ltp_fremovexattr01_fix.patch
> ++       remove(FNAME);
use SAFE_REMOVE()

2020-05-21 17:46 UTC, hukoyu commented on tests/ltp/patches/ltp_fremovexattr01_fix.patch
> ++       rmdir(MNTPOINT);
SAFE_RMDIR()

2020-05-21 17:46 UTC, hukoyu commented on tests/ltp/patches/ltp_fremovexattr01_fix.patch
> ++       rmdir(MNTPOINT);
SAFE_RMDIR()

2020-05-21 17:46 UTC, hukoyu commented on tests/ltp/patches/ltp_fremovexattr02_fix.patch
> ++       remove(FNAME);
SAFE_REMOVE()

2020-05-21 17:46 UTC, hukoyu commented on tests/ltp/patches/ltp_fremovexattr02_fix.patch
> +++      rmdir(MNTPOINT);
SAFE_RMDIR

2020-05-21 17:46 UTC, hukoyu commented on tests/ltp/patches/ltp_fremovexattr02_fix.patch
> ++       rmdir(MNTPOINT);
SAFE_RMDIR

2020-05-22 08:59 UTC, hukoyu requested changes
Refer to issue https://github.com/lsds/sgx-lkl/issues/297 not 169

2020-05-22 08:59 UTC, hukoyu commented on tests/ltp/patches/ltp_fremovexattr02_fix.patch
> ++//     {                               /* case 3: bad name attribute */ TODO: Will be enabled once issue 169 is fixed
Change to https://github.com/lsds/sgx-lkl/issues/297

2020-05-22 09:51 UTC, hukoyu approved these changes
LGTM. cc @letmaik

2020-05-27 18:12 UTC, letmaik approved these changes

2020-05-27 18:12 UTC, merged