LTP: fix test case sendfile09 issue
lsds/sgx-lkl pull request #300
Opened 2020-05-22 11:58 UTC by shaikshavali1

In original test case, below two issues are found.
    1.4GB file is used for verifying the “sendfile()”
      system call. As memory in sgx-lkl environment
      is limited, hence, testing with 4GB file is
      not supported.
    2.During setup (in setup())a check is performed
      to verify availability of 5GB free space in
      filesystem. The 5GB free space verification is
      failed because information returned by statfs()
      system call is erroneous. Git hub issue
      “https://github.com/lsds/sgx-lkl/issues/288”
      is raised
Above mentioned issues are addressed in this patch.
Below changes are performed.
    1.In this patch 4GB file size is reduced to 4MB.
    2.5GB free space check is modified to 5MB and
      commented the check. This check has to be
      uncommented as soon as git hub issue
      “https://github.com/lsds/sgx-lkl/issues/288”
      resolved.

2020-05-22 16:10 UTC, ashokchandran commented
Reviewed the changes. No issues observed.

2020-05-22 20:05 UTC, hukoyu commented
@shaikshavali1 please sync with upstream and resolve the conflicts.

2020-05-22 20:26 UTC, hukoyu approved these changes
LGTM. cc @letmaik

2020-05-22 20:27 UTC, hukoyu requested changes
Plelase sycn with upstream and resolve conflicts.

2020-05-27 18:11 UTC, letmaik approved these changes

2020-05-27 18:17 UTC, letmaik commented
Please resolve conflict

2020-05-28 21:52 UTC, hukoyu commented
@letmaik synced with upstream and conflicts resolved. Ready to be merged.

2020-05-29 01:46 UTC, hukoyu approved these changes

2020-05-29 01:46 UTC, merged