removexattr01 fix
lsds/sgx-lkl pull request #373
Opened 2020-06-03 14:51 UTC by ashokchandran

Issue: Root file system is not mounted with xattr option so test was failing as it needs xattr support.
Solution: Mount file system with user_xattr enabled and run the test using it.

2020-06-03 15:51 UTC, ashokchandran commented
Failures are in unrelated tests 
languages-python-(debug)-(run-hw)-(8-ethreads)languages-java-thread-(nonrelease)-(run-hw)-(8-ethreads) failing in enclave initialization due to sgxlkl_enclave_init failure.

2020-06-03 18:42 UTC, hukoyu requested changes
@ashokchandran please pay attention to coding styles. 
- Indentation
- Space after commas
Otherthan that looks good.

2020-06-03 18:42 UTC, hukoyu commented on tests/ltp/patches/removexattr01.patch
> ++#define FILENAME "mntpoint/removexattr01testfile"
Fix indentation. Please apply coding style standards.

2020-06-03 18:42 UTC, hukoyu commented on tests/ltp/patches/removexattr01.patch
> ++	SAFE_MKDIR(cleanup,MNTPOINT, DIR_MODE);
Space after commo

2020-06-03 18:42 UTC, hukoyu commented on tests/ltp/patches/removexattr01.patch
> ++	SAFE_MOUNT(cleanup,device, MNTPOINT, fs_type, 0, "user_xattr");
Space after comma

2020-06-03 18:42 UTC, hukoyu commented on tests/ltp/patches/removexattr01.patch
> ++	SAFE_UMOUNT(NULL,MNTPOINT);
Space after comma

2020-06-03 18:42 UTC, hukoyu commented on tests/ltp/patches/removexattr01.patch
> ++	SAFE_RMDIR(NULL,MNTPOINT);
Space after comma

2020-06-04 05:47 UTC, ashokchandran commented on tests/ltp/patches/removexattr01.patch
> ++	SAFE_MOUNT(cleanup,device, MNTPOINT, fs_type, 0, "user_xattr");
done

2020-06-04 05:47 UTC, ashokchandran commented on tests/ltp/patches/removexattr01.patch
> ++	SAFE_MKDIR(cleanup,MNTPOINT, DIR_MODE);
done

2020-06-04 05:48 UTC, ashokchandran commented on tests/ltp/patches/removexattr01.patch
> ++#define FILENAME "mntpoint/removexattr01testfile"
done

2020-06-04 05:48 UTC, ashokchandran commented on tests/ltp/patches/removexattr01.patch
> ++	SAFE_UMOUNT(NULL,MNTPOINT);
done

2020-06-04 05:48 UTC, ashokchandran commented on tests/ltp/patches/removexattr01.patch
> ++	SAFE_RMDIR(NULL,MNTPOINT);
done

2020-06-04 06:03 UTC, hukoyu requested changes

2020-06-04 06:03 UTC, hukoyu commented on tests/ltp/patches/removexattr01.patch
> ++	n = setxattr( FILENAME, USER_KEY, VALUE, VALUE_SIZE, XATTR_CREATE);
no space before FILENAME

2020-06-04 06:03 UTC, hukoyu commented on tests/ltp/patches/removexattr01.patch
> ++	TEST(removexattr( FILENAME, USER_KEY));
no space before FILENAME

2020-06-04 06:03 UTC, hukoyu commented on tests/ltp/patches/removexattr01.patch
> ++	n = getxattr( FILENAME, USER_KEY, buf, size);
no space before FILENAME

2020-06-04 06:57 UTC, ashokchandran commented on tests/ltp/patches/removexattr01.patch
> ++	n = setxattr( FILENAME, USER_KEY, VALUE, VALUE_SIZE, XATTR_CREATE);
done

2020-06-04 06:57 UTC, ashokchandran commented on tests/ltp/patches/removexattr01.patch
> ++	TEST(removexattr( FILENAME, USER_KEY));
done

2020-06-04 06:57 UTC, ashokchandran commented on tests/ltp/patches/removexattr01.patch
> ++	n = getxattr( FILENAME, USER_KEY, buf, size);
done

2020-06-04 21:20 UTC, hukoyu approved these changes
LGTM

2020-06-04 21:20 UTC, merged