LTP: Fixed getxattr04 testcase
lsds/sgx-lkl pull request #426
Opened 2020-06-10 14:27 UTC by vamsikrishna935

Modified the tests to use root file system.

2020-06-10 15:35 UTC, shaikshavali1 commented on tests/ltp/patches/ltp_getxattr04_fix.patch
> ++ // So modified the tests to use root file system.
You can write these lines without "//" .

2020-06-10 15:35 UTC, shaikshavali1 commented on tests/ltp/patches/ltp_getxattr04_fix.patch
> ++//     while (!end) {
if this line not required then delete the line instead of commenting.

2020-06-10 15:35 UTC, shaikshavali1 commented on tests/ltp/patches/ltp_getxattr04_fix.patch
> +-       SAFE_SIGNAL(SIGUSR1, sigproc);
Please check why this line showing as a change.

2020-06-10 15:35 UTC, shaikshavali1 commented on tests/ltp/patches/ltp_getxattr04_fix.patch
> ++
please remove this additional  new line.

2020-06-10 18:53 UTC, hukoyu requested changes
@vamsikrishna935  please address @shaikshavali1  's comments and submit your commit and resolve feedback.

2020-06-11 20:24 UTC, hukoyu approved these changes
LGTM

2020-06-11 20:24 UTC, merged