LTP: Fixed fdatasync03 testcase
lsds/sgx-lkl pull request #436
Opened 2020-06-11 08:11 UTC by vamsikrishna935

Patch Description: Tests were failing with kernel panic in loop filesystem. 
So modified the tests to use root file system.

2020-06-11 12:31 UTC, shaikshavali1 requested changes
@vamsikrishna935 , Please address the comments

2020-06-11 12:31 UTC, shaikshavali1 commented on tests/ltp/patches/ltp_fdatasync_fdatasync03_fix.patch
> +-
check formatting issues

2020-06-11 12:31 UTC, shaikshavali1 commented on tests/ltp/patches/ltp_fdatasync_fdatasync03_fix.patch
> ++       SAFE_MOUNT("/dev/vda", MNTPOINT, "ext4", 0, NULL);
better define "/dev/vda" as a  macro.

2020-06-12 18:03 UTC, hukoyu approved these changes
LGTM

2020-06-12 18:03 UTC, merged