LTP: Fixed fallocate04 and fallocate05 testcases
lsds/sgx-lkl pull request #675
Opened 2020-07-24 15:28 UTC by vamsikrishna935

Tests were failing with Kernel panic (out of memory) in loop device.
loop device filesystem is having a limit of 32MB
So modified the tests using root filesystem.

2020-07-25 07:24 UTC, davidchisnall commented
I think this patch is fine, but please can we track the tests that are failing because we don't have enough kernel memory centrally?  These should all be revisited after #597 is fixed.

2020-07-25 07:24 UTC, davidchisnall approved these changes

2020-07-26 01:36 UTC, hukoyu requested changes
@vamsikrishna935 please change patch file names as suggested. Afte rthat we can merge this PR.

2020-07-26 01:36 UTC, hukoyu commented on tests/ltp/patches/ltp_fallocate_fallocate04_fix.patch
> ++ Tesst Failure reason:
Can you change the patch file name to fallocate04.patch
You can run 
git mv ltp_fallocate_fallocate04_fix.patch  fallocate04.patch

2020-07-26 01:36 UTC, hukoyu commented on tests/ltp/patches/ltp_fallocate_fallocate05_fix.patch
> ++ Test failure reason:
Can you change the patch file name to fallocate05.patch
You can run 
git mv ltp_fallocate_fallocate05_fix.patch  fallocate05.patch

2020-07-28 04:14 UTC, hukoyu approved these changes
LGTM

2020-07-28 04:14 UTC, merged